### ISSUE TITLE
Overriding VERSION_ID in /etc/os-release causes tce-load mirror URL to break

### ISSUE THREAD

**Issue by trinitronx** [silver886/boot2docker#37]
It looks like the [`Dockerfile` build overrides `VERSION_ID` in `/etc/os-release`][1].  This is used by the `getMirror` function in `/etc/init.d/tc-functions` to find the `MIRROR` URL.

As a result, any `tce-load` or `tce` install command will fail with `404` error, because the `20.10.11` Boot2Docker version does not match the current repo mirror URL for Tiny Core Linux version (`12.0` => `12.x`):  `http://repo.tinycorelinux.net/12.x/x86_64/tcz/`

Example:

```
tce-load -wi python
Downloading: python.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
wget: server returned error: HTTP/1.1 404 Not Found
md5sum: python.tcz.md5.txt: No such file or directory
Error on python.tcz
```

## Workaround

Replace the `VERSION_ID` with current TCL version: `12.0`:

    sudo /bin/sed -i'' -e 's/VERSION_ID=.*/VERSION_ID=12.0/'  /etc/os-release

Now `tce-load` works again:

```
tce-load -wi python'
python.tcz.dep OK
readline.tcz.dep OK
[...SNIP...] # Lots of dependencies here...
Downloading: python.tcz
Connecting to repo.tinycorelinux.net (89.22.99.37:80)
saving to 'python.tcz'
python.tcz             1% |                                |  145k  0:01:16 ETA
[...SNIP...]
python.tcz            83% |**************************      | 9399k  0:00:01 ETA
python.tcz           100% |********************************| 10.9M  0:00:00 ETA
'python.tcz' saved
python.tcz: OK
```

#### Debugging

To check the resulting `MIRROR` url:

    . /etc/init.d/tc-functions ; set -x; getMirror ; set +x

##### Output:

```
+ getMirror
+ BUILD=
+ '[' -z '' ']'
++ getBuild
+++ uname -m
++ BUILD=x86_64
++ case ${BUILD} in
++ '[' -f /lib/ld-linux-x86-64.so.2 ']'
++ echo x86_64
+ BUILD=x86_64
+ read MIRROR
++ getMajorVer
+++ getFullVer
++++ grep '^VERSION_ID=' /etc/os-release
+++ verid=VERSION_ID=12.0
+++ echo 12.0
++ fullver=12.0
++ echo 12
+ MIRROR=http://repo.tinycorelinux.net/12.x/x86_64/tcz
+ set +x
```

[1]: https://github.com/silver886/boot2docker/blob/d2571721a65490acc6606b173c146521040a6c4f/Dockerfile#L456

**Comment by silver886** [comment]
Thank you for the issue, I never use `tce-load` in the image . . .😅

After some researching, I assumed that `VERSION_ID` only impacts `/etc/init.d/tc-functions`.

[`v20.10.12-rc1`](https://github.com/silver886/boot2docker/releases/tag/v20.10.12-rc1) fixed the issue by patching `/etc/init.d/tc-functions`.
Please let me know if this fixes the issue and won't cause side effect in your scenario.

**Comment by silver886** [comment]
It's my fault that didn't notice your PR #38.
I'd like to keep `VERSION_ID` and `VERSION` are related, let me know your thought.

**Comment by trinitronx** [comment]
@silver886  My apologies for not replying sooner! (busy with work)

I was able to find some time to test this, and it does fix the issue!  Tested with:

```bash
BOOT2DOCKER_URL='https://github.com/silver886/boot2docker/releases/download/v20.10.12-rc1/boot2docker.iso'

 docker-machine create --driver virtualbox \
   --virtualbox-boot2docker-url "$BOOT2DOCKER_URL" \
   --virtualbox-hostonly-cidr "192.168.56.100/21" \
   dm-test

DOCKER_MACHINE_NAME=$(docker-machine active 2>/dev/null)
[ -z $DOCKER_MACHINE_NAME ] && DOCKER_MACHINE_NAME=$(docker-machine active | head -n1)
[ -z $DOCKER_MACHINE_NAME ] && errorout "Cannot find active docker-machine name... make sure the VM is running"

eval $(docker-machine env $DOCKER_MACHINE_NAME)

docker-machine ssh $DOCKER_MACHINE_NAME  'tce-load -wi ntpclient.tcz'
```

Installed new `boot2docker.iso`, started the VM, and loaded the `ntpclient.tcz` package successfully!

Thanks for fixing this issue!
